"""Run LLM-assisted description cleaning for preprocessed action units.

Input files are pickled dictionaries generated by the preprocessing stage:
    token_units_dir/us_unit_{item}.pkl

The script writes one LLM result and one verification result per item under
the requested output directory.
"""

from __future__ import annotations

import argparse
import json
import pickle
from itertools import product
from pathlib import Path

from openrouter_client import OpenRouterPipeline
from prompts import prompt, verify_prompt


LLM_ACTION_TYPES = {
    "menu",
    "toolbar",
    "button",
    "textbox_onfocus",
    "textbox_killfocus",
    "combobox",
    "textlink",
}


def iter_items() -> list[str]:
    return [f"ps{i}_{j}" for i, j in product(range(1, 3), range(1, 8))]


def load_unit_dictionary(path: Path) -> dict:
    with path.open("rb") as handle:
        return pickle.load(handle)


def prepare_llm_input(unit_dict: dict) -> str:
    filtered = {key: value for key, value in unit_dict.items() if key in LLM_ACTION_TYPES}
    return json.dumps(filtered, ensure_ascii=False, indent=2)


def run_item(
    item: str,
    token_units_dir: Path,
    output_dir: Path,
    client: OpenRouterPipeline,
) -> None:
    input_path = token_units_dir / f"us_unit_{item}.pkl"
    unit_dict = load_unit_dictionary(input_path)
    llm_input = prepare_llm_input(unit_dict)

    main_result = client.run(prompt, llm_input)
    verify_result = client.run(verify_prompt, main_result)

    item_output_dir = output_dir / item
    item_output_dir.mkdir(parents=True, exist_ok=True)
    (item_output_dir / "step1_llm.txt").write_text(main_result, encoding="utf-8")
    (item_output_dir / "step1_llm_verify.txt").write_text(verify_result, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--token-units-dir", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, default=Path("mapping_tables"))
    parser.add_argument("--item", choices=iter_items(), help="Run a single item only.")
    parser.add_argument("--model", default="anthropic/claude-sonnet-4.5")
    args = parser.parse_args()

    client = OpenRouterPipeline(model=args.model)
    items = [args.item] if args.item else iter_items()

    for item in items:
        run_item(item, args.token_units_dir, args.output_dir, client)
        print(f"saved LLM mapping for {item}")


if __name__ == "__main__":
    main()
